name: Deploy web app

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Install packages
        run: bun install

      - name: Build app
        run: bun run build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Deploy to Google Cloud
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ./dist
          destination: cu-dbmi-static-sites/ghostbusters
          parent: false
